apiVersion: apps/v1
kind: Deployment
metadata:
  name: misp-redis
  namespace: misp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misp-redis
  template:
    metadata:
      labels:
        app: misp-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: misp-redis
  namespace: misp
spec:
  selector:
    app: misp-redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis