apiVersion: v1
kind: Service
metadata:
  name: misp-app
  namespace: misp
spec:
  type: ClusterIP
  selector:
    app: misp-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
# Optional: NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: misp-app-external
  namespace: misp
spec:
  type: NodePort
  selector:
    app: misp-app
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30080