controller:
  # Run on control plane nodes only
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  
  # Allow scheduling on control plane (bypass taints)
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  
  # Lightweight configuration
  replicaCount: 1
  
  # Resource limits for testing
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  # Service configuration
  service:
    type: NodePort
    externalTrafficPolicy: Local
    
  # Ingress class configuration
  ingressClass: nginx
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  
  # Disable unnecessary features for testing
  config:
    ssl-redirect: "false"
    force-ssl-redirect: "false"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    
  # Disable admission webhook for testing
  admissionWebhooks:
    enabled: false
    
  # Metrics (optional)
  metrics:
    enabled: false
    
  # Disable default backend
  defaultBackend:
    enabled: false

# Disable RBAC if needed (not recommended for production)
rbac:
  create: true

# Service account
serviceAccount:
  create: true