deploymentMode: SingleBinary<->SimpleScalable
singleBinary:
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
 
test:
  enabled: false
 
loki:
  auth_enabled: false
  image:
    pullPolicy: IfNotPresent
 
  commonConfig:
    replication_factor: 1
 
  storage:
    type: filesystem
    filesystem:
      directory: /var/loki
 
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
 
  compactor:
    retention_enabled: false
 
  limits_config:
    allow_structured_metadata: false
    volume_enabled: false
 
# Disable all components not needed in singleBinary
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
 
minio:
  enabled: false
 
gateway:
  enabled: false
 
write:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: standard  # adjust to your cluster's default
 
serviceMonitor:
  enabled: false
 
chunksCache:
  enabled: false
 
resultsCache:
  enabled: false
 
lokiCanary:
  enabled: false